# Generated by Django 6.1.1 on 2026-10-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductBacklog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projeto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_backlog",
                        to="core.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Epico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epicos",
                        to="core.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SprintBacklog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Ex: Sprint 1", max_length=100)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprint_backlogs",
                        to="core.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "papel",
                    models.CharField(help_text="Como um [papel]...", max_length=100),
                ),
                (
                    "acao",
                    models.CharField(help_text="Eu quero [ação]...", max_length=255),
                ),
                (
                    "beneficio",
                    models.CharField(help_text="Para [benefício]...", max_length=255),
                ),
                ("contexto", models.TextField(help_text="Dado [contexto inicial]...")),
                (
                    "evento",
                    models.CharField(help_text="Quando [evento]...", max_length=255),
                ),
                ("resultado", models.TextField(help_text="Então [resultado]...")),
                (
                    "story_points",
                    models.IntegerField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (5, "5"),
                            (8, "8"),
                            (13, "13"),
                            (21, "21"),
                            (34, "34"),
                            (55, "55"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "moscow",
                    models.CharField(
                        choices=[
                            ("M", "Must Have"),
                            ("S", "Should Have"),
                            ("C", "Could Have"),
                            ("W", "Won't Have"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "reach",
                    models.IntegerField(
                        default=0, help_text="Alcance (Número de usuários)"
                    ),
                ),
                (
                    "impact",
                    models.FloatField(
                        choices=[
                            (3.0, "Massivo"),
                            (2.0, "Alto"),
                            (1.0, "Médio"),
                            (0.5, "Baixo"),
                            (0.25, "Mínimo"),
                        ],
                        default=1.0,
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        choices=[
                            (100, "Alta (100%)"),
                            (80, "Média (80%)"),
                            (50, "Baixa (50%)"),
                        ],
                        default=80,
                    ),
                ),
                (
                    "epico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historias",
                        to="core.epico",
                    ),
                ),
                (
                    "product_backlog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historias",
                        to="core.productbacklog",
                    ),
                ),
                (
                    "sprint_backlog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historias",
                        to="core.sprintbacklog",
                    ),
                ),
            ],
        ),
    ]
